// (c) by Stefan Roettger, licensed under GPL 2+

#ifndef VIEWERCONST_H
#define VIEWERCONST_H

#define VIEWER_WIDTH 768
#define VIEWER_MINWIDTH 256
#define VIEWER_ASPECT 1.0f

#define VIEWER_FOGSTART 0.1f
#define VIEWER_FOGEND 1.0f
#define VIEWER_FOGDENSITY 0.75f

#define VIEWER_VOIDSTART 100000.0f
#define VIEWER_ABYSSSTART -500.0f

#define VIEWER_EXAGGER 3.0f
#define VIEWER_RES 1.0E4f
#define VIEWER_RELRES 0.25f
#define VIEWER_RANGE 0.01f
#define VIEWER_RELRANGE 0.25f
#define VIEWER_SEALEVEL -MAXFLOAT
#define VIEWER_LEVELS 5
#define VIEWER_CONTOURS 100.0f
#define VIEWER_SEABOTTOM -1000.0f

#define CAMERA_FPS 30.0f

#define CAMERA_FOVY 90.0f
#define CAMERA_NEARP 50.0f
#define CAMERA_FARP 1.0E7f

#define CAMERA_HEIGHT 3.0E6f
#define CAMERA_HEIGHT_FLOOR (2.0f*CAMERA_NEARP)
#define CAMERA_LAT 21.39
#define CAMERA_LON -157.72

#endif
