# Defines
#  ICONV_FOUND
#  ICONV_INCLUDE_DIR
#  ICONV_LIBRARIES

FIND_PATH(ICONV_INCLUDE_DIR iconv.h DOC "Directory containing libiconv headers")
FIND_LIBRARY(ICONV_LIBRARY NAMES iconv DOC "Path to libiconv library")

SET(ICONV_LIBRARIES ${ICONV_LIBRARY})

IF (ICONV_LIBRARY AND ICONV_INCLUDE_DIR)
   SET(ICONV_FOUND TRUE)
   MESSAGE(STATUS "Found libiconv: ${ICONV_LIBRARY}")
ENDIF (ICONV_LIBRARY AND ICONV_INCLUDE_DIR)
