# Defines
#  MINI_FOUND
#  MINI_INCLUDE_DIR
#  MINI_LIBRARIES

FIND_PATH(MINI_INCLUDE_DIR mini/mini.h PATHS . .. ../deps DOC "Directory containing Mini headers")
FIND_LIBRARY(MINI_LIBRARY NAMES Mini libMini PATHS . .. ../mini ../deps/mini DOC "Path to Mini library")
FIND_LIBRARY(MINI_LIBRARY_DEBUG NAMES Minid libMinid PATHS . .. ../mini ../deps/mini DOC "Path to Mini library")

IF (MINI_LIBRARY AND MINI_INCLUDE_DIR)
   SET(MINI_LIBRARIES ${MINI_LIBRARIES} optimized ${MINI_LIBRARY})
   SET(MINI_FOUND)
ENDIF (MINI_LIBRARY AND MINI_INCLUDE_DIR)

IF (MINI_LIBRARY_DEBUG AND MINI_INCLUDE_DIR)
   SET(MINI_LIBRARIES ${MINI_LIBRARIES} debug ${MINI_LIBRARY_DEBUG})
   SET(MINI_FOUND)
ENDIF (MINI_LIBRARY_DEBUG AND MINI_INCLUDE_DIR)
