#ifndef CAMERACONST_H
#define CAMERACONST_H

#define CAMERA_FPS 30.0f

#define CAMERA_FOVY 90.0f
#define CAMERA_NEARP 50.0f
#define CAMERA_FARP 1.0E7f

#define CAMERA_HEIGHT 3.0E6f
#define CAMERA_HEIGHT_FLOOR (2.0f*CAMERA_NEARP)
#define CAMERA_LAT 21.39
#define CAMERA_LON -157.72

#define CAMERA_SBASE 100.0f

#endif
